### PR TITLE
Remove numerical recipes, 2nd attempt 

### PR DESCRIPTION
**Pull request by olebole**
This is a followup to #2, with the first patch split up.

This pull request is a follow-up to a [discussion on the starlink-devel mailing list](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A1=ind1602&L=STARDEV#1).

The Numerical Recipes code is not allowed to redistribute; see http://numerical.recipes/licenses/redistribute.html

Numerical recipes code is used Skycat in `rtd/generic/iqefunc.c` and in cfitsio. This patch replaces `iqefunc.c` by the version from [ESO-MIDAS 15SEPpl1.0](ftp://ftp.eso.org/pub/midaspub/15SEP/sources/15SEPpl1.0.tar.gz) which uses `mpfit.c` instead of `mrqfit.c`. Differently to the solution in ESO-MIDAS, the sort function was replaced by the libc `qsort()`.

Note that the file `astrotcl/cfitsio/eval_y.c` still contains NR code; the whole `astrotcl/cfitsio` subdirectory should be updated with the latest version of cfitsio (which does not contain code from the Numerical Recipes anymore).

### CODE REVIEW

**Comment by pwdraper** [comment]
Thanks Ole, initial tests look promising, so I'm accepting this push with one fix as
you removed the `iqefunc.c` file by mistake.

**Comment by olebole** [comment]
Oops. Sorry.

**Comment by pwdraper** [comment]
BTW, for comparison to Skycat you will need to cherry pick these fixes to the vendor branch.
That contains the unmodified version of Skycat.

**Comment by olebole** [comment]
OK, thanks. I'll send a notification to ESO.

**Pull request merged**
